### ISSUE TITLE
make  error

### ISSUE THREAD

**Issue by yuanwb1984** [hotpaw2/hfp_tcp#7]
# make hfp_tcp
Building for Linux
cc -I/usr/local/include/libairspyhf  hfp_tcp_server.c -o hfp_tcp -std=c99 -lm -lairspyhf
/usr/bin/ld: /tmp/ccF7ISB4.o: undefined reference to symbol 'pthread_create@@GLIBC_2.4'
/usr/bin/ld: //lib/arm-linux-gnueabihf/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:17: hfp_tcp] Error 1

**Comment by WB2ISS** [comment]
The latest version of the source uses pthread but the Makefile wasn't updated.    See pull request for modifications.
